### ISSUE TITLE
[Feature] Myfile page

### ISSUE THREAD

**Issue by kiwi142857** [Okabe-Rintarou-0/SJTU-Canvas-Helper#27]
Canvas上有我的文件页面，可以查看提交过的作业or 保存的文件  https://oc.sjtu.edu.cn/files/folder/users_xxxxxx/%E6%8F%90%E4%BA%A4%E6%96%87%E4%BB%B6/ 
希望实现该页面
![image](https://github.com/Okabe-Rintarou-0/SJTU-Canvas-Helper/assets/122582483/2f6196f3-4b5a-4e6a-b329-50b9c9fd032c)

**Comment by Okabe-Rintarou-0** [comment]
已在最新版实现。

**Comment by kiwi142857** [comment]
感谢！！
一个小建议：选中文件夹后网页自动转到最上方，（目前的版本中选中文件夹若在较下方，点进后页面显示保留在下部分，想查看文件得回滚到页面上方）））  只是一点点用户体验（），再次感谢~

**Comment by Okabe-Rintarou-0** [comment]
最新版已改进。

**Comment by kiwi142857** [comment]
谢谢~~
