### ISSUE TITLE
PDF/PPT合并能否推测合并顺序，并让用户微调？

### ISSUE THREAD

**Issue by WindOct** [Okabe-Rintarou-0/SJTU-Canvas-Helper#29]
现在将PDF/PPT合并的顺序依赖于用户选择文件的顺序，如果可以做成先根据文件名或文件时间等智能推断大致顺序，然后让用户自行微调是否会更好捏

**Comment by WindOct** [comment]
或者在文件选择界面做个按名称排序（）

**Comment by Okabe-Rintarou-0** [comment]
感谢建议，我觉得确实可以改进

**Comment by Okabe-Rintarou-0** [comment]
已实现该功能

**Comment by WindOct** [comment]
> 已实现该功能

好快😮👍🐂

**Comment by Okabe-Rintarou-0** [comment]
> > 已实现该功能
> 
> 好快😮👍🐂

先根据文件名或文件时间等智能推断大致顺序，这个忘记实现了，乐，不过现在可以调整顺序了，初始顺序为文件在canvas中的顺序，不过老师一般会按照顺序上传的

**Comment by WindOct** [comment]
> 不过现在可以调整顺序了
有这个差不多也就够了，一般上传的文件命名也有规律
赞一个👍
